# This file defines all the model deployments that are supported by the Helm API.
# Some models have several deployments, each with different parameters.

# If you want to add a new deployment, you can technically do it here but we recommend
# you to do it in private/model_deployments.yaml instead.

model_deployments:

  # ========== AI21 Labs ========== #

  # J1 models are Deprecated by AI21 Labs
  # API returns: Detail: Jurassic J1 models are deprecated
  - name: ai21/j1-jumbo # DEPRECATED
    model_name: ai21/j1-jumbo
    tokenizer_name: ai21/j1
    client_spec:
      class_name: "helm.proxy.clients.ai21_client.AI21Client"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.ai21_window_service.AI21WindowService"
      args:
        gpt2_window_service:
          class_name: "helm.benchmark.window_services.gpt2_window_service.GPT2WindowService"
          args: {}

  - name: ai21/j1-large # DEPRECATED
    model_name: ai21/j1-large
    tokenizer_name: ai21/j1
    client_spec:
      class_name: "helm.proxy.clients.ai21_client.AI21Client"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.ai21_window_service.AI21WindowService"
      args:
        gpt2_window_service:
          class_name: "helm.benchmark.window_services.gpt2_window_service.GPT2WindowService"
          args: {}

  - name: ai21/j1-grande # DEPRECATED
    model_name: ai21/j1-grande
    tokenizer_name: ai21/j1
    client_spec:
      class_name: "helm.proxy.clients.ai21_client.AI21Client"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.ai21_window_service.AI21WindowService"
      args:
        gpt2_window_service:
          class_name: "helm.benchmark.window_services.gpt2_window_service.GPT2WindowService"
          args: {}

  - name: ai21/j1-grande-v2-beta # DEPRECATED
    model_name: ai21/j1-grande-v2-beta
    tokenizer_name: ai21/j1
    client_spec:
      class_name: "helm.proxy.clients.ai21_client.AI21Client"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.ai21_window_service.AI21WindowService"
      args:
        gpt2_window_service:
          class_name: "helm.benchmark.window_services.gpt2_window_service.GPT2WindowService"
          args: {}

  - name: ai21/j2-jumbo
    model_name: ai21/j2-jumbo
    tokenizer_name: ai21/j1
    client_spec:
      class_name: "helm.proxy.clients.ai21_client.AI21Client"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.wider_ai21_window_service.AI21Jurassic2JumboWindowService"
      args:
        gpt2_window_service:
          class_name: "helm.benchmark.window_services.gpt2_window_service.GPT2WindowService"
          args: {}

  - name: ai21/j2-large
    model_name: ai21/j2-large
    tokenizer_name: ai21/j1
    client_spec:
      class_name: "helm.proxy.clients.ai21_client.AI21Client"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.wider_ai21_window_service.WiderAI21WindowService"
      args:
        gpt2_window_service:
          class_name: "helm.benchmark.window_services.gpt2_window_service.GPT2WindowService"
          args: {}

  - name: ai21/j2-grande
    model_name: ai21/j2-grande
    tokenizer_name: ai21/j1
    client_spec:
      class_name: "helm.proxy.clients.ai21_client.AI21Client"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.wider_ai21_window_service.WiderAI21WindowService"
      args:
        gpt2_window_service:
          class_name: "helm.benchmark.window_services.gpt2_window_service.GPT2WindowService"
          args: {}
  # =============================== #



  # ========== Aleph Alpha ========== #
  - name: AlephAlpha/luminous-base
    model_name: AlephAlpha/luminous-base
    tokenizer_name: AlephAlpha/luminous-base
    client_spec:
      class_name: "helm.proxy.clients.aleph_alpha_client.AlephAlphaClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.luminous_window_service.LuminousBaseWindowService"
      args: {}

  - name: AlephAlpha/luminous-extended
    model_name: AlephAlpha/luminous-extended
    tokenizer_name: AlephAlpha/luminous-extended
    client_spec:
      class_name: "helm.proxy.clients.aleph_alpha_client.AlephAlphaClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.luminous_window_service.LuminousExtendedWindowService"
      args: {}

  - name: AlephAlpha/luminous-supreme
    model_name: AlephAlpha/luminous-supreme
    tokenizer_name: AlephAlpha/luminous-supreme
    client_spec:
      class_name: "helm.proxy.clients.aleph_alpha_client.AlephAlphaClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.luminous_window_service.LuminousSupremeWindowService"
      args: {}

  # TODO: Add luminous-world once it is released.
  # ================================= #


  
  # =========== Anthropic =========== #
  - name: anthropic/claude-v1.3
    model_name: anthropic/claude-v1.3
    tokenizer_name: anthropic/claude
    client_spec:
      class_name: "helm.proxy.clients.anthropic_client.AnthropicClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.anthropic_window_service.AnthropicWindowService"
      args: {}

  - name: anthropic/claude-instant-v1
    model_name: anthropic/claude-instant-v1
    tokenizer_name: anthropic/claude
    client_spec:
      class_name: "helm.proxy.clients.anthropic_client.AnthropicClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.anthropic_window_service.AnthropicWindowService"
      args: {}

  - name: anthropic/claude-2.0
    model_name: anthropic/claude-2.0
    tokenizer_name: anthropic/claude
    client_spec:
      class_name: "helm.proxy.clients.anthropic_client.AnthropicClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.anthropic_window_service.AnthropicWindowService"
      args: {}

  - name: anthropic/stanford-online-all-v4-s3
    model_name: anthropic/stanford-online-all-v4-s3
    tokenizer_name: huggingface/gpt2
    client_spec:
      class_name: "helm.proxy.clients.anthropic_client.AnthropicLegacyClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.anthropic_window_service.LegacyAnthropicWindowService"
      args: {}
  # ================================= #



  # =========== BigScience =========== #
  - name: together/bloom
    model_name: bigscience/bloom
    tokenizer_name: bigscience/bloom
    client_spec:
      class_name: "helm.proxy.clients.together_client.TogetherClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.bloom_window_service.BloomWindowService"
      args: {}

  - name: together/t0pp
    model_name: bigscience/t0pp
    tokenizer_name: bigscience/T0pp
    client_spec:
      class_name: "helm.proxy.clients.together_client.TogetherClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.t0pp_window_service.T0ppWindowService"
      args: {}
  # ================================== #



  # =========== BigCode =========== #
  - name: huggingface/santacoder
    model_name: bigcode/santacoder
    tokenizer_name: bigcode/santacoder
    client_spec:
      class_name: "helm.proxy.clients.huggingface_client.HuggingFaceClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.santacoder_window_service.SantaCoderWindowService"
      args: {}

  - name: huggingface/starcoder
    model_name: bigcode/starcoder
    tokenizer_name: bigcode/starcoder
    client_spec:
      class_name: "helm.proxy.clients.huggingface_client.HuggingFaceClient"
      args: {}
    window_service_spec:
      class_name: "helm.benchmark.window_services.starcoder_window_service.StarCoderWindowService"
      args: {}
  # =============================== #