---
############################################################
# For backwards compatibility with older versions of HELM.
# TODO: Remove this after 2024-09-01.
adapter: []
############################################################
perturbations:
  - name: robustness
    display_name: Robustness
    description: Computes worst case over different robustness perturbations (misspellings, formatting, contrast sets).

############################################################
metrics:
  # Accuracy metrics:
  - name: exact_match
    display_name: Exact match
    short_display_name: EM
    description: Fraction of instances that the predicted output matches a correct reference exactly.
    lower_is_better: false
  - name: quasi_exact_match
    display_name: Quasi-exact match
    short_display_name: EM
    description: Fraction of instances that the predicted output matches a correct reference up to light processing.
    lower_is_better: false
  - name: prefix_exact_match
    display_name: Prefix exact match
    short_display_name: PEM
    description: Fraction of instances that the predicted output matches the prefix of a correct reference exactly.
    lower_is_better: false


############################################################
metric_groups:
  - name: accuracy
    display_name: Accuracy
    metrics:
      - name: ${main_name}
        split: ${main_split}

############################################################
run_groups:
  - name: core_scenarios
    display_name: Core scenarios
    description: The scenarios where we evaluate all the models.
    category: All scenarios
    subgroups:
      - viz_wiz

  - name: heim_human_eval
    display_name: HEIM Human Eval Scenario for VLMs
    description: Measuring how well VLMs can evaluate images generated by text-to-image models.
    metric_groups:
      - accuracy
    environment:
      main_name: exact_match
      main_split: test
    taxonomy:
      task: multimodal multiple-choice question answering
      what: Art & Design, Business, Science, Health & Medicine, Humanities & Social Science, and Tech & Engineering
      who: Human experts
      when: "2023"
      language: English
